# Description: Creates a deployment and service for Gogs, with a mount to the local filesystem
# Author: retgits
# Last Updated: 2018-10-24
# 
# Deploy Gogs
#   kubectl apply -f gogs.yml
# Make sure the service is created correctly
#   kubectl get service | grep gogs
# Open the URL
#   open https://localhost:31818
---
#--- Gogs Deployment ---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: gogs
  name: gogs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: gogs
  template:
    metadata:
      labels:
        run: gogs
    spec:
      volumes:
      - name: gogs-data-volume
        hostPath:
          path: /Users/lstigter/storage/gogs
      containers:
      - name: gogs
        image: gogs/gogs:latest
        volumeMounts:
        - mountPath: /data
          name: gogs-data-volume
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
#--- Gogs Service ---
apiVersion: v1
kind: Service
metadata:
  name: gogs-http
  labels:
    app: gogs
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31818
  selector:
    run: gogs